Documentation:
- changed-files:
  - any-glob-to-any-file: ['docs/*', '**/*.md']
enhancement:
 - head-branch: ['^feature', 'feature', 'Feature']
bug-fix:
 - head-branch: ['^fix', 'fix', '^bugfix', 'bugfix']
testing:
- changed-files:
  - any-glob-to-any-file: ['test/*', '**/*_test.jl']
