name: Close Milestones and Move Issues
on:
  pull_request:
  schedule:
    - cron: '0 1 * * *' # Runs at midnight every day at 1:00 AM
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  close-and-move-milestones:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: List milestones
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/milestones > milestones.json
          echo "milestones=$(cat milestones.json)" >> $GITHUB_ENV

      - name: Find past due milestones
        run: |
          current_date=$(date -u +"%Y-%m-%dT00:00:00Z")
          past_due_milestones=$(jq -r --arg current_date "$current_date" '
            .[] | select(.due_on != null and .due_on < $current_date) | .number' milestones.json)
          echo "past_due_milestones=$past_due_milestones" >> $GITHUB_ENV

      - name: Add comment to issues and PRs in past due milestones
        if: env.past_due_milestones != ''
        run: |
          for milestone_number in $(echo "$past_due_milestones"); do
            issues=$(gh api -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/issues?milestone=$milestone_number)
            for issue in $(echo "$issues" | jq -r '.[].number'); do
              gh api -X POST -H "Accept: application/vnd.github+json" \
                /repos/${{ github.repository }}/issues/$issue/comments \
                -f body="This issue/PR belongs to the milestone $milestone_number which is past due and will be closed. Please update the milestone accordingly."
            done
          done

      - name: Close past due milestones
        if: env.past_due_milestones != ''
        run: |
          for milestone_number in $(echo "$past_due_milestones"); do
            gh api -X PATCH -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/milestones/$milestone_number \
              -f state=closed
          done
