name: PR Labeler
on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    steps:
      - name: Print GitHub Refs
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
      - uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/label.yml
