name: PR Labeler
on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/label.yml
