name: Register
on:
  push:
    branches:
      - main
    tags: ['*']
  workflow_dispatch:
jobs:
  Register:
    name: Build, precompile and register the Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDS}}
      - name: Add JuliaRegistry
        run: |
          julia -e 'using Pkg; Pkg.add("LocalRegistry")'
          julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/ManojDattatrayaBhat/JuliaRegistry.git"))'
          julia -e 'using Pkg.Registry; Registry.update()'
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - name: Precompile
        run: julia --project -e 'using Pkg; Pkg.precompile()'
      - name: Set up Git
        run: |
          git config --global user.email "${{github.event.pusher.email}}"
          git config --global user.name "${{ github.actor }}"
      - name: register
        run: julia --project -e 'using LocalRegistry; using MyJuliaPackage; register(; ignore_reregistration = true)'
