name: TagBot
on:
  push:
    branch:
      - main
  workflow_dispatch:
    inputs:
      lookback:
        default: 3
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDS}}
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.TAGBOT_TOKEN }}
          registry: ManojDattatrayaBhat/JuliaRegistry
          changelog: |
            This is release {{ version }} of {{ package }}.
            {% if previous_release %}
            Diff since {{ previous_release }}]({{ compare_url }})
            {% endif %}
            {% if custom %}
            {{ custom }}
            {% endif %}
            {% if pulls %}
            **Merged pull requests:**
            {% for pull in pulls %}
            - {{ pull.title }} (#{{ pull.number }}) (@{{ pull.author.username }})
            {% endfor %}
            {% if issues %}
            **Closed issues:**
            {% for issue in issues %}
            - {{ issue.title }} (#{{ issue.number }})
            {% endfor %}
            {% endif %}
            {% endif %}