name: Unittest
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-runtest@v1
