name: Unittest
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/CI.yml
      - uses: julia-actions/julia-runtest@v1
