name: Unittest
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
jobs:
  test:
    steps:
      - uses: ./.github/workflows/CI.yml@build
      - uses: julia-actions/julia-runtest@v1
